# Generated by Django 5.2 on 2025-04-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linkedin_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
